version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -a
    silent: true

  test:
    desc: Run asdf plugin tests
    cmds:
      - asdf plugin test helmfile . "helmfile version"

  format:
    desc: Format bash scripts with shfmt
    cmds:
      - |
        shfmt --language-dialect bash --write \
          ./**/*